nnine-tech/nnine-training

public/markdown/courselist.md
src/Syllabus/Flutter.js
src/Syllabus/PythonSyllabus.js
src/app/Syllabus/Flutter/page.js

feat: Flutter syllabus & css added
feat: Flutter syllabus & css added

feat: Flutter syllabus & css added

---

src/components/Card2.js
src/components/CourseList.js
yarn.lock

feat: course-card-design
```bash
type: feat: course-card-design
```
```bash
version: feat: course-card-design
```

feat: course-card-design

---

package.json

feat: courseModel and courseSyllabusModel created

---

backend/.gitignore
backend/Controller/courseController.js
backend/Model/courseModel.js
backend/Model/coursesyllabusModel.js
backend/Routes/courseRoute.js
backend/app.js
backend/config.env
backend/package-lock.json
backend/package.json
backend/server.js

setup done

---

src/components/AWSDevelopmentSyllabus1.js
src/components/AWSSolutionSyllabus1.js
src/components/AspNetSyllabus1.js
src/components/AwsCloudSyllabus1.js
src/components/BasicComputerSyllabus1.js
src/components/CourseSlide.js
src/components/CourseSyllabus1.js
src/components/DataScienceAndMLSyllabus1.js
src/components/DevopsSyllabus1.js
src/components/DigitalMarketingSyllabus1.js
src/components/EthicalHackingSyllabus1.js
src/components/FlutterSyllabus1.js
src/components/GraphicDesignSyllabus1.js
src/components/OpenShiftSyllabus1.js
src/components/PyhtonDjangoSyllabus1.js
src/components/PythonSyllabus1.js
src/components/QASyllabus1.js
src/components/RedHatAdministratorSyllabus1.js
src/components/RedHatOpenShiftSyllabus1.js
src/components/UIUXSyllabus1.js
src/components/WebdevelopmentSyllabus1.js

feat: font change

---

src/components/LandingTrainers.js

feat: LandingTrainers Updated

---

src/components/Career.js
src/components/LandingTrainers.js

feat: careerUpdated

---

public/aboutbg.svg
public/aboutbg2.svg
src/app/Popularcourses/page.js
src/components/About.js
src/components/Blogs.js
src/components/Card2.js
src/components/CourseList.js

feat: initial update

---

backend/Controller/studentController.js
backend/Model/studentModel.js
backend/Routes/studentRoute.js
backend/app.js
backend/config.env
backend/package-lock.json
backend/package.json

106 student api

---

backend/.gitignore
backend/Controller/courseController.js
backend/Model/coursesyllabusModel.js
backend/Model/newCourseModel.js
backend/Routes/courseRoute.js
backend/app.js
backend/server.js

feat: course,syllabus model updated

---

backend/Controller/courseController.js
backend/Controller/courseSyllabusController.js
backend/Model/coursesyllabusModel.js
backend/Routes/courseRoute.js
backend/Routes/courseSyllabusRoute.js
backend/Utils/apiFeatures.js
backend/package.json

feat: course controller updated

---

backend/Controller/notificationController.js
backend/Model/notificationModel.js
backend/Routes/notificationRoute.js
backend/app.js

feat:notification API

---

backend/Controller/courseController.js
backend/Controller/feesController.js

feat: fix bug

---

src/components/Footer.js

feat: changes

---

backend/Controller/adminController.js
backend/Controller/authenticationController.js
backend/Controller/courseController.js
backend/Model/newAdminModel.js
backend/Routes/adminRoute.js
backend/Routes/courseRoute.js
backend/app.js
backend/config.env

fix: beautify

---

backend/Controller/feesController.js
backend/Controller/messageController.js
backend/Model/fee.model.js
backend/Routes/feesRoute.js
backend/app.js
backend/package-lock.json
backend/package.json

feat: fee API

---

backend/Controller/feesController.js
backend/Controller/messageController.js
backend/Controller/studentController.js
backend/Model/studentModel.js
backend/Routes/feesRoute.js
backend/Routes/studentRoute.js
backend/app.js
backend/config.env

feat: Student Enrollment

---

src/components/AWSDevelopmentSyllabus1.js
src/components/AWSSolutionSyllabus1.js
src/components/About.js
src/components/AspNetSyllabus1.js
src/components/AwsCloudSyllabus1.js
src/components/BasicComputerSyllabus1.js
src/components/CPlusSyllabus1.js
src/components/CourseSyllabus1.js
src/components/DataScienceAndMLSyllabus1.js
src/components/DevopsSyllabus1.js
src/components/DigitalMarketingSyllabus1.js
src/components/EthicalHackingSyllabus1.js
src/components/FlutterSyllabus1.js
src/components/GraphicDesignSyllabus1.js
src/components/OpenShiftSyllabus1.js
src/components/PyhtonDjangoSyllabus1.js
src/components/PythonSyllabus1.js
src/components/QASyllabus1.js
src/components/RedHatAdministratorSyllabus1.js
src/components/RedHatOpenShiftSyllabus1.js
src/components/UIUXSyllabus1.js
src/components/WebdevelopmentSyllabus1.js

feat: syllabus spacing updated

feat: syllabus spacing updated

---

src/components/Footer.js

fix: minor changes
fix: minor changes

fix: minor changes

---

src/components/CourseSlide.js
src/components/Footer.js

feat: courses slide button change

feat: courses slide button change

---

src/components/AWSDevelopmentSyllabus1.js
src/components/AWSSolutionSyllabus1.js
src/components/AspNetSyllabus1.js
src/components/AwsCloudSyllabus1.js
src/components/BasicComputerSyllabus1.js
src/components/CPlusSyllabus1.js
src/components/CourseSyllabus1.js
src/components/DataScienceAndMLSyllabus1.js
src/components/DevopsSyllabus1.js
src/components/DigitalMarketingSyllabus1.js
src/components/EthicalHackingSyllabus1.js
src/components/FlutterSyllabus1.js
src/components/GraphicDesignSyllabus1.js
src/components/OpenShiftSyllabus1.js
src/components/PyhtonDjangoSyllabus1.js
src/components/PythonSyllabus1.js
src/components/QASyllabus1.js
src/components/RedHatAdministratorSyllabus1.js
src/components/RedHatOpenShiftSyllabus1.js
src/components/UIUXSyllabus1.js
src/components/WebdevelopmentSyllabus1.js

feat: syllabus modification

---

package-lock.json
package.json
src/components/About.js
src/components/Navbar2.js
tailwind.config.js
yarn.lock

feat: about-us-responsive
feat: about-us-responsive
```bash
feat: about-us-responsive

217 about us responsive

---

src/components/About.js
tailwind.config.js

feat: about-us-change
feat: about-us-change
```bash
feat: about-us-change
```

219 about us change

---

src/components/Footer.js
src/components/UIUXClassType.js
src/components/UIUXSyllabus1.js

feat: course-width-change
feat: course-width-change
```bash
feat: course-width-change
```

feat: course-width-change

---

src/components/UIUXClassType.js
src/components/UIUXSyllabus1.js

feat: footer-and-course
feat: footer-and-course
```bash
feat: footer-and-course```

feat: footer-and-course

---

src/components/About.js

feat: about-responsive-large
feat: about-responsive-large
```bash
feat: about-responsive-large
```

feat: about-responsive-large

---

attendance-be/models/associations.js
attendance-be/models/attendance.model.js
attendance-be/models/holiday.model.js
attendance-be/models/user.model.js
attendance-be/models/workschedule.model.js
attendance-be/package-lock.json
attendance-be/package.json
attendance-be/src/app.js
attendance-be/src/controllers/attendance.controller.js
attendance-be/src/controllers/auth.controller.js
attendance-be/src/controllers/holiday.controller.js
attendance-be/src/controllers/user.controller.js
attendance-be/src/controllers/workSchedule.controller.js
attendance-be/src/index.js
attendance-be/src/routes/holiday.router.js
attendance-be/src/routes/user.router.js
attendance-be/src/routes/workSchedule.rouer.js
attendance-be/src/services/attendance.service.js
attendance-be/src/services/holiday.service.js
attendance-be/src/services/token.service.js
attendance-be/src/services/user.service.js
attendance-be/src/services/workSchedule.service.js
attendance-be/src/validators/user.validate.js

feat: attendace enhance

---

attendance-be/models/leaveRequest.model.js
attendance-be/models/user.model.js
attendance-be/src/app.js
attendance-be/src/controllers/attendance.controller.js
attendance-be/src/controllers/leaveRequest.controller.js
attendance-be/src/controllers/user.controller.js
attendance-be/src/middlewares/authManagerOnly.js
attendance-be/src/routes/leaveRequest.router.js
attendance-be/src/services/attendance.service.js
attendance-be/src/services/leaveRequest.service.js
attendance-be/src/services/user.service.js
attendance-be/src/validators/leaveRequest.validate.js
attendance-be/src/validators/user.validate.js

feat: leave request

---

src/app/layout.js
src/components/Navbar.js
src/components/SPSSintro.js

feat: navbar changes
feat: navbar changes

feat: navbar changes

---

package-lock.json
src/app/layout.js
src/app/page.js
yarn.lock

feat: for-search-optimization
feat: for-search-optimization
```bash
feat: for-search-optimization
```

feat: for-search-optimization

---

public/markdown/syllabus/devops.md
src/components/DevopsSyllabus1.js

feat: devops-markdown-syllabus
feat: devops-markdown-syllabus
```bash
feat: devops-markdown-syllabus
```

feat: devops-markdown-syllabus

---

public/markdown/syllabus/mernstack.md
src/components/CourseSyllabus1.js

feat: mern-markdown-edit
feat: mern-markdown-edit
```bash
feat: mern-markdown-edit
```

feat: mern-markdown-edit

---

public/markdown/syllabus/python.md
public/markdown/syllabus/uiux.md
src/components/PythonSyllabus1.js

feat: python-markdown-added
feat: python-markdown-added
```bash
feat: python-markdown-added
```

feat: python-markdown-added

---

public/markdown/syllabus/python.md
public/markdown/syllabus/webdevelopment.md
src/components/CourseSyllabus1.js
src/components/PythonSyllabus1.js
src/components/UIUXSyllabus1.js
src/components/WebdevelopmentSyllabus1.js

feat: webdev-markdown-added
feat: webdev-markdown-added
```bash
feat: webdev-markdown-added
```

feat: webdev-markdown-added

---

public/markdown/syllabus/datascienceandml.md
src/components/DataScienceAndMLSyllabus1.js

feat: data-ml-markdown-added
feat: data-ml-markdown-added
```bash
feat: data-ml-markdown-added
```

feat: data-ml-markdown-added

---

src/components/Footer.js
src/components/Navbar.js

feat: blog-navigation-solved
feat: blog-navigation-solved
```bash
feat: blog-navigation-solved
```

feat: blog-navigation-solved

---

public/markdown/syllabus/aspdotnet.md
public/markdown/syllabus/awscloud.md
public/markdown/syllabus/digitalmarketing.md
public/markdown/syllabus/ethicalhacking.md
public/markdown/syllabus/graphicdesign.md
public/markdown/syllabus/pythondjango.md
src/components/AspNetSyllabus1.js
src/components/AwsCloudSyllabus1.js
src/components/DataScienceAndMLSyllabus1.js
src/components/DigitalMarketingSyllabus1.js
src/components/EthicalHackingSyllabus1.js
src/components/GraphicDesignSyllabus1.js
src/components/PyhtonDjangoSyllabus1.js

feat: all-markdown-added
feat: all-markdown-added
```bash
feat: all-markdown-added
```

feat: all-markdown-added
